server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-authentication-method: client_secret_post
            provider: keycloak
            client-id: coldbrew-gateway

            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:8081/login/oauth2/code/keycloak
            scope:
              - openid
        provider:
          keycloak:
            jwk-set-uri: http://localhost:8180/realms/coldbrew/protocol/openid-connect/certs
            issuer-uri: http://localhost:8180/realms/coldbrew
            authorization-uri: http://localhost:8180/realms/coldbrew/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/coldbrew/protocol/openid-connect/token
            user-info-uri: http://localhost:8180/realms/coldbrew/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
